### ISSUE TITLE
Detekcja ruchu i bezruchu HMC5883L

### ISSUE THREAD

**Issue by roblad** [jarzebski/Arduino-HMC5883L#4]
Detekcja ruchu i bezruchu

czy ma ktos jakis przyklad z wyzwalaniem przerwania DRDY i budzenia arduino ze stanu uspienia.

Dzieki

**Comment by MatthewPatyk** [comment]
Jeśli chodzi o wykorzystanie przerwania DRDY to najlepiej wykorzystać funkcje `attachInterrupt`:

`pinMode(DRDY_PIN, INPUT_PULLUP);`
`attachInterrupt(DRDY_PIN, isr, FALLING);`

Następnie w procedurze obsługi przerwania `isr` ustawiać flagę, potem gdzieś w kodzie wykonywać odczyt danych z HMC5883L jeśli flaga została ustawiona.

Jeśli zależy Ci na odczycie z maksymalną prędkością `160 Hz` to po każdym odczycie danych należy ponownie ustawić tryb `Single-Measurement Mode` w rejestrze `Mode Register (0x02)` magnetometru, ponieważ po każdym wystawieniu `DRDY` urządzenie przechodzi w tryb `Idle Mode`.
